import StyledComponentsRegistry from "@/lib/registry";
import type { Metadata } from "next";
import { ResetCss } from "@/styles/reset";

import { Ubuntu } from "next/font/google";
import { LightProvider } from "@/context/LightContext";

const ubuntu = Ubuntu({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ResetCss />
      <html lang="en">
        <body className={ubuntu.className}>
          <LightProvider>
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          </LightProvider>
        </body>
      </html>
    </>
  );
}
